Update day 2 content
Sydney-Informatics-Hub/hello-nextflow pull request #4
Opened 2024-08-16 06:47 UTC by fredjaya

Addresses #2 (thanks @christopher-hakkaart!).

Ready for another round of feedback on the docs and content. I haven't timed it properly, but I think there might be too much content at the moment. 

**Key changes and additions:**
- Uses samplesheet for loading reads
- Individual docker containers used, and introduced early on
- Remove `log.info` for now

**Other:**
- Add more self-guided exercises
- a lot of renaming, moving stuff around and formatting

2024-08-16 06:48 UTC, fredjaya commented
Can't assign as reviewer, but feedback from you would be great! @christopher-hakkaart

2024-08-19 11:35 UTC, christopher-hakkaart commented
Sorry - I'm still getting to this! I'm swamped with work. I'll start chipping away at it now.

2024-08-20 08:02 UTC, georgiesamaha requested changes
Looking good but a few things we should chat about: 

* Add an experimental scenario to contextualise what we're doing. This should translate to other applications. 
* Add a section to explain what/when/why workflows are a good option and when they arent, tie this to nextflow's strengths. 
* Each section should contain a set of learning objectives so we set expectations and people know what they're working on in each section 
* Sections should be renamed to focus on nextflow implementation, not RNAseq 
* How we can rearrange things to build on knowledge, rather than implement different things at different points and clearly explain and justify the added complexity of using nextflow by comparing to a basic bash implementation.

2024-08-20 23:01 UTC, fredjaya commented on docs/01_salmon_idx.md
> +## 2.1.3 Save files to an output directory with `publishDir`
There's an explanation in day 1 content (`session1/02_hellonf.md` [L141](https://github.com/Sydney-Informatics-Hub/hello-nextflow/pull/3/files#)), can add a "recall that..."

2024-08-20 23:24 UTC, fredjaya commented on docs/03_fastqc.md
I think because it was the order in the source material. Would make sense to move this before all the groovy and operators

2024-08-20 23:37 UTC, fredjaya commented on docs/01_salmon_idx.md
> +## 2.1.3 Save files to an output directory with `publishDir`
(and 03_output.md)

2024-08-20 23:50 UTC, fredjaya commented
Summary of feedback from Chris:
- Spell out every little detail
- Review every piece of code and check whether prior explanation exists or link out
- Wary of time, possibly drop part 5, introduce multiple samples shortly after `params.reads`

2024-08-23 00:43 UTC, merged